### ISSUE TITLE
尝试编译运行React的例子，出现报错。

### ISSUE THREAD

**Issue by awong1900** [befovy/node-addon-starter#1]
非常好的例子，非常感谢分享。
![image](https://user-images.githubusercontent.com/4022612/71615776-d93b3100-2bed-11ea-96f3-86252af7658a.png)

**Comment by befovy** [comment]
@awong1900 你好
这个是运行在浏览器中报错还是在启动的electron窗口中报错？

**Comment by awong1900** [comment]
浏览器打开的报错。

**Comment by befovy** [comment]
浏览器不支持的，用不了。
只能在 electron app 窗口中使用。

**Comment by awong1900** [comment]
哦。 这样我其实说错了，是打开的npm start 打开的app 里面报错的。 因为就是web嘛，我说成浏览器了。

**Comment by befovy** [comment]
@awong1900  npm start 打开的是浏览器，但是这种插件不支持运行在浏览器中。 
运行 npm start 的目的不是打开浏览器，是启动 React 页面。所以应该加个什么参数让 npm start 别打开浏览器了
